<a href="https://colab.research.google.com/github/ghostriley08/Deep-Learning-using-Fastai-and-Pytorch/blob/main/notebooks/Deep_Learning_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import numpy as np
# Tensor can be created from numpy arrays or lists
list = [[1,2,3],[4,5,6]]
numpy_array = np.array(list)
tensor = torch.tensor(list)
tensor1 = torch.tensor(numpy_array)
print(tensor)
print(tensor1)
# Tensor attributes
print(tensor.shape)
print(tensor1.dtype)


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


In [11]:
# Tensor operations ----- Shape must be exactly the same
print(tensor + tensor1)
print(tensor - tensor1)
print(tensor * tensor1) # Elementwise multiplication
print(tensor / tensor1)
print(torch.transpose(tensor,0,1)@tensor1) #Matrix multiplication

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[17, 22, 27],
        [22, 29, 36],
        [27, 36, 45]])
