<a href="https://colab.research.google.com/github/ghostriley08/Deep-Learning-using-Fastai-and-Pytorch/blob/main/notebooks/Into_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np
# Tensor can be created from numpy arrays or lists
list = [[1,2,3],[4,5,6]]
numpy_array = np.array(list)
tensor = torch.tensor(list)
tensor1 = torch.tensor(numpy_array)
print(tensor)
print(tensor1)
# Tensor attributes
print(tensor.shape)
print(tensor1.dtype)


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


In [4]:
# Tensor operations ----- Shape must be exactly the same
print(tensor + tensor1)
print(tensor - tensor1)
print(tensor * tensor1) # Elementwise multiplication
print(tensor / tensor1)
print(torch.transpose(tensor,0,1)@tensor1) #Matrix multiplication

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[17, 22, 27],
        [22, 29, 36],
        [27, 36, 45]])


In [11]:
# Designing a neural network
import torch.nn as nn
input_tensor = torch.tensor([[1,2,3],[4,5,6]]).float() # Cast to float
linear_layer = nn.Linear(in_features=3,out_features = 2)
output = linear_layer(input_tensor) # We can call this object like a function because PyTorch classes use Python's __call__ method.
print(output)
print(linear_layer.weight) # Weight is importance of each feature
print(linear_layer.bias) # Bias is baseline output
# Different outputs need different math, so each output gets its own dedicated
# weights for the input features.

tensor([[-0.0557],
        [-0.8552]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[ 0.0241, -0.4724,  0.1817]], requires_grad=True)
Parameter containing:
tensor([0.3197], requires_grad=True)


In [27]:
model = nn.Sequential(
    nn.Linear(in_features=3,out_features=2),
    nn.Linear(in_features=2,out_features=4),
    nn.Linear(in_features=4,out_features=6),
) # Creates a neural network with 3 input_features , output features = 6
  # More hidden layers more model capacity
total = 0
for parameter in model.parameters():
  total = total + parameter.numel()
print(total)
# Calculates total number of parameters in the netwrok

50
